Feedback/Controllers/HistoryController.cs
using Feedback.Models;
using LNF.Cache;
using System;
using System.Web.Mvc;

namespace Feedback.Controllers
{
    public class HistoryController : Controller
    {
        [HttpGet, Route("history")]
        public ActionResult Index()
        {
            ViewBag.Tab = "history";
            ViewBag.Submenu = 1;
            ViewBag.DisplayName = CacheManager.Current.CurrentUser.DisplayName;

            HistoryModel model = new HistoryModel()
            {
                ClientID = CacheManager.Current.CurrentUser.ClientID,
                FeedbackStatus = "All",
                StartDate = DateTime.Now.Date.AddMonths(-6),
                EndDate = DateTime.Now.Date.AddDays(1),
                DateRangePreset = null
            };

            return View(model);
        }

        [HttpPost, Route("history")]
        public ActionResult Index(HistoryModel model)
        {
            ViewBag.Tab = "history";
            ViewBag.Submenu = 1;
            ViewBag.DisplayName = CacheManager.Current.CurrentUser.DisplayName;

            if (model.RetrieveData)
                model.DateRangePreset = null;

            return View(model);
        }

        [HttpGet, Route("history/report")]
        public ActionResult AggregateReport()
        {
            ViewBag.Tab = "history";
            ViewBag.Submenu = 2;
            ViewBag.DisplayName = CacheManager.Current.CurrentUser.DisplayName;
            return View();
        }

        [HttpPost, Route("history/report")]
        public ActionResult AggregateReport(HistoryModel model)
        {
            ViewBag.Tab = "history";
            ViewBag.Submenu = 2;
            ViewBag.DisplayName = CacheManager.Current.CurrentUser.DisplayName;
            return View(model);
        }

        [Route("history/dispute")]
        public ActionResult Dispute()
        {
            ViewBag.Tab = "history";
            ViewBag.Submenu = 3;
            return View();
        }

        [Route("history/negative/detail/{issueId}")]
        public ActionResult NegativeDetail(int issueId)
        {
            ViewBag.Tab = "history";
            ViewBag.Submenu = 1;
            var issue = ReportUtility.GetNegativeIssue(issueId);
            return View(issue);
        }
    }
}

Feedback/Controllers/SummaryController.cs
using System.Web.Mvc;

namespace Feedback.Controllers
{
    public class SummaryController : Controller
    {
        [Route("summary")]
        public ActionResult Index()
        {
            ViewBag.Tab = "summary";
            return View();
        }
    }
}

Feedback/Views/Shared/_Layout.cshtml
@{
    string tab = ViewBag.Tab;

    Func<string, string> getTabClass = x =>
    {
        if (x == tab)
        {
            return "active";
        }
        else
        {
            return string.Empty;
        }
    };
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="//ssel-apps.eecs.umich.edu/static/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="//ssel-apps.eecs.umich.edu/static/lib/bootstrap/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link href="~/Content/Site.css" rel="stylesheet" />

    @RenderSection("styles", false)
</head>
<body class="feedback" data-apiurl="@Url.Content("~/api/")">
    <div class="container-fluid">
        <h3 style="margin-bottom: 20px;">LNF Feedback</h3>

        <ul class="nav nav-tabs">
            <li role="presentation" class="@getTabClass("positive")">@Html.ActionLink("Positive Feedback", "Positive", "Home")</li>
            <li role="presentation" class="@getTabClass("negative")">@Html.ActionLink("Negative Feedback", "Negative", "Home")</li>
            <li role="presentation" class="@getTabClass("history")">@Html.ActionLink("My History", "Index", "History")</li>
            <li role="presentation" class="@getTabClass("summary")">@Html.ActionLink("Feedback Summary", "Index", "Summary")</li>
            <li role="presentation" class="@getTabClass("admin")">@Html.ActionLink("Admin", "Index", "Admin")</li>
        </ul>

        <div style="margin-top: 20px; margin-bottom: 20px;">
            @RenderBody()
        </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//ssel-apps.eecs.umich.edu/static/lib/jquery/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="//ssel-apps.eecs.umich.edu/static/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="//ssel-apps.eecs.umich.edu/static/lib/bootstrap/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>

    <script src="//ssel-apps.eecs.umich.edu/static/lib/moment/moment.min.js"></script>

    <script src="~/Scripts/feedback.js"></script>

    <script>
        $(".feedback").feedback();
    </script>

    @RenderSection("scripts", false)
</body>
</html>